# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76cb4dd65ad5aa33457063af4974c2e3efc6ce650b1119443c0dfb47d57ad355d7d1cb1eecd4bfec942c0c2cc28fd59b3162b472a1a4321c9f6f42786e1ac34

test:
  secret_key_base: 65f7b5a11a3ab0012de50a558d38df48965b71225cc7b0d87357eec43470f414b690e917aea8860241796088304b8f345339f13a431a6e2b99ad78cec7d66bcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
